# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('letter_yr', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('login', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('student_letter_yr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Classes')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.People'),
        ),
    ]
