# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='student_letter_yr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kateapp.Classes'),
        ),
        migrations.AlterField(
            model_name='people',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kateapp.People'),
        ),
    ]
