# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0003_auto_20161119_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(default='Term', max_length=200),
            preserve_default=False,
        ),
    ]
