# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0004_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='assessment',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='exercise_type',
            field=models.CharField(choices=[('CW', 'Coursework'), ('PROJ', 'Project'), ('REP', 'Report'), ('T', 'Test'), ('WES', 'Exam'), ('TUT', 'Tutorial')], default='CW', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercises',
            name='submission',
            field=models.CharField(choices=[('HARDCOPY', 'Hardcopy'), ('ELECTRONIC', 'Electronic')], max_length=15, null=True),
        ),
    ]
