# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0005_auto_20161122_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='assessment',
            field=models.CharField(choices=[(None, 'No Assessment'), ('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='submission',
            field=models.CharField(choices=[(None, 'No submission'), ('HARDCOPY', 'Hardcopy'), ('ELECTRONIC', 'Electronic')], default=None, max_length=15, null=True),
        ),
    ]
