# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0006_auto_20161122_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='assessment',
            field=models.CharField(blank=True, choices=[(None, 'No Assessment'), ('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='submission',
            field=models.CharField(blank=True, choices=[(None, 'No submission'), ('HARDCOPY', 'Hardcopy'), ('ELECTRONIC', 'Electronic')], default=None, max_length=15, null=True),
        ),
    ]
