# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0014_auto_20161122_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='path/')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses_resource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Resource'),
        ),
    ]
