# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0015_auto_20161122_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Exercises')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Resource')),
            ],
        ),
    ]
