# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0016_exercises_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
