# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0016_exercises_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='esubmission_files_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
