# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0019_auto_20161126_1446'),
        ('kateapp', '0017_auto_20161122_2206'),
    ]

    operations = [
    ]
