# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0020_merge_20161130_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Exercises')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='registered_courses',
            field=models.ManyToManyField(related_name='registered', to='kateapp.Courses'),
        ),
        migrations.AddField(
            model_name='people',
            name='required_courses',
            field=models.ManyToManyField(related_name='required', to='kateapp.Courses'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='submissions',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='kateapp.People'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='members',
            field=models.ManyToManyField(related_name='members', to='kateapp.People'),
        ),
    ]
