# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0021_auto_20161130_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_resource',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='courses_resource',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('EXERCISE', 'Exercise'), ('URL', 'Url'), ('PANOPTO', 'Panopto')], default='NOTE', max_length=15),
        ),
        migrations.AddField(
            model_name='exercises_resource',
            name='type',
            field=models.CharField(choices=[('SPEC', 'Specification'), ('DATA', 'Data files'), ('ANSWER', 'Model answer'), ('MARKING', 'Marking scheme')], default='SPEC', max_length=15),
        ),
        migrations.AddField(
            model_name='submissions',
            name='files',
            field=models.ManyToManyField(to='kateapp.Resource'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courses_resource',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kateapp.Resource'),
        ),
    ]
