# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0022_auto_20161130_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.Exercises')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kateapp.People')),
            ],
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='mark',
        ),
    ]
