# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0023_auto_20161201_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_resource',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercises_resource',
            name='type',
            field=models.CharField(choices=[('SPEC', 'Specification'), ('DATA', 'Data file'), ('ANSWER', 'Model answer'), ('MARKING', 'Marking scheme')], default='SPEC', max_length=15),
        ),
    ]
