# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0024_auto_20161201_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises_resource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kateapp.Resource'),
        ),
    ]
