# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0025_courses_resource_timestamp'),
        ('kateapp', '0025_auto_20161201_1426'),
    ]

    operations = [
    ]
