# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0026_merge_20161201_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_resource',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='courses_resource',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses_resource',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kateapp.Resource'),
        ),
        migrations.AlterField(
            model_name='courses_resource',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('PROBLEM', 'Problem'), ('URL', 'Url'), ('PANOPTO', 'Panopto')], default='NOTE', max_length=15),
        ),
    ]
