# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0027_auto_20161201_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
