# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0028_marks_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
