# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0030_exercises_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises_resource',
            old_name='type',
            new_name='resource_type',
        ),
    ]
