# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0031_auto_20170106_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses_resource',
            old_name='type',
            new_name='course_resource_type',
        ),
        migrations.RenameField(
            model_name='exercises_resource',
            old_name='resource_type',
            new_name='exercise_resource_type',
        ),
    ]
