# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0033_auto_20170110_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='released',
        ),
        migrations.AddField(
            model_name='exercises',
            name='mark_released_date',
            field=models.DateTimeField(null=True),
        ),
    ]
