# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0034_auto_20170110_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='mark_released_date',
            new_name='mark_release_date',
        ),
    ]
