# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0035_auto_20170110_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='released',
        ),
    ]
