# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kateapp', '0037_remove_exercises_marked'),
        ('kateapp', '0037_marks_released'),
    ]

    operations = [
    ]
